<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Core\DoNotPanicPortfolioVisualizer.Core.csproj" />
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Shared\DoNotPanicPortfolioVisualizer.Shared.csproj" />
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Data\DoNotPanicPortfolioVisualizer.Data.csproj" />
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Media\DoNotPanicPortfolioVisualizer.Media.csproj" />
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Render\DoNotPanicPortfolioVisualizer.Render.csproj" />
    <ProjectReference Include="..\..\src\DoNotPanicPortfolioVisualizer.Presentation\DoNotPanicPortfolioVisualizer.Presentation.csproj" />
    <ProjectReference Include="..\..\src\YFinance\YFinance.NET\YFinance.NET.csproj" />
  </ItemGroup>

</Project>
